<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';

type ChallengeShape = Record<string, unknown>;

interface ProofBundle {
  version: number;
  type: 'privacysafe_identity_link_v1';
  privacysafe_user_id: string;
  signed_at: string;
  challenge: ChallengeShape;
  payload_canonical_json: string;
  mailerid_signature: web3n.mailerid.MailerIdSignature;
}

const enc = new TextEncoder();
const nomenWebUrl = ((import.meta.env.VITE_NOMEN_WEB_URL as string | undefined)?.trim() || 'https://nomen.provable.dev');

const userId = ref('');
const appVersion = ref('');
const challengeInput = ref(`{
  "nomen_user_id": "",
  "nonce": "",
  "issued_at": "",
  "expires_at": ""
}`);
const errorMessage = ref('');
const successMessage = ref('');
const proofJson = ref('');
const isSigning = ref(false);
const isCopying = ref(false);

const canSign = computed(() => (
  !isSigning.value &&
  !!userId.value &&
  challengeInput.value.trim().length > 0
));

function sortValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortValue);
  }
  if (value && typeof value === 'object') {
    return Object.keys(value as Record<string, unknown>)
      .sort()
      .reduce<Record<string, unknown>>((acc, key) => {
        acc[key] = sortValue((value as Record<string, unknown>)[key]);
        return acc;
      }, {});
  }
  return value;
}

function toCanonicalJson(value: unknown): string {
  return JSON.stringify(sortValue(value));
}

function parseChallenge(): ChallengeShape {
  let parsed: unknown;
  try {
    parsed = JSON.parse(challengeInput.value);
  } catch {
    throw new Error('Challenge must be valid JSON.');
  }

  if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') {
    throw new Error('Challenge must be a JSON object.');
  }

  return parsed as ChallengeShape;
}

async function signChallenge() {
  errorMessage.value = '';
  successMessage.value = '';

  if (!w3n.mailerid) {
    errorMessage.value = 'MailerId capability is not available in this app runtime.';
    return;
  }

  try {
    isSigning.value = true;
    const challenge = parseChallenge();
    const signedAt = new Date().toISOString();
    const payload = {
      type: 'privacysafe_identity_link_v1',
      privacysafe_user_id: userId.value,
      challenge,
      signed_at: signedAt,
    };
    const payloadCanonicalJson = toCanonicalJson(payload);
    const signature = await w3n.mailerid.sign(enc.encode(payloadCanonicalJson));

    const proof: ProofBundle = {
      version: 1,
      type: 'privacysafe_identity_link_v1',
      privacysafe_user_id: userId.value,
      signed_at: signedAt,
      challenge,
      payload_canonical_json: payloadCanonicalJson,
      mailerid_signature: signature,
    };

    proofJson.value = `${JSON.stringify(proof, null, 2)}\n`;
    successMessage.value = 'Signed proof generated. Paste this JSON into Nomen.';
  } catch (err) {
    errorMessage.value = err instanceof Error ? err.message : 'Signing failed.';
    proofJson.value = '';
  } finally {
    isSigning.value = false;
  }
}

async function copyProof() {
  if (!proofJson.value) {
    return;
  }

  try {
    isCopying.value = true;
    await navigator.clipboard.writeText(proofJson.value);
    successMessage.value = 'Signed proof copied to clipboard.';
  } catch (err) {
    errorMessage.value = err instanceof Error ? err.message : 'Copy to clipboard failed.';
  } finally {
    isCopying.value = false;
  }
}

async function openDashboard() {
  await w3n.shell?.openDashboard?.();
}

async function openNomen() {
  await w3n.shell?.openURL?.(nomenWebUrl);
}

onMounted(async () => {
  try {
    if (w3n.mailerid) {
      userId.value = await w3n.mailerid.getUserId();
    }
    if (w3n.myVersion) {
      appVersion.value = (await w3n.myVersion()) ?? '';
    }
  } catch (err) {
    errorMessage.value = err instanceof Error ? err.message : 'Failed to load PrivacySafe identity.';
  }
});
</script>

<template>
  <div class="shell">
    <header class="topbar">
      <button class="brand" type="button" @click="openDashboard">
        <img src="/logo.png" alt="Nomen" class="brand__logo">
        <span class="brand__name">Nomen</span>
      </button>
      <div class="meta">
        <div class="meta__label">PrivacySafe identity</div>
        <div class="meta__value">{{ userId || 'Unavailable' }}</div>
        <div v-if="appVersion" class="meta__version">v{{ appVersion }}</div>
      </div>
    </header>

    <main class="content">
      <section class="panel panel--intro">
        <h1>Use PrivacySafe with Nomen</h1>
        <p>
          Paste the JSON challenge generated by Nomen, then sign it with your current PrivacySafe MailerId identity.
          This works for both linking your PrivacySafe identity to Nomen and signing back into Nomen later.
        </p>
        <div class="actions">
          <button class="btn" type="button" @click="openNomen">
            Open Nomen
          </button>
        </div>
      </section>

      <section class="grid">
        <section class="panel panel--form">
          <div class="panel__header">
            <h2>Nomen challenge</h2>
            <span class="panel__hint">JSON object from Nomen</span>
          </div>
          <textarea
            v-model="challengeInput"
            class="editor"
            spellcheck="false"
            autocomplete="off"
          />
          <div class="actions">
            <button class="btn btn--primary" :disabled="!canSign" type="button" @click="signChallenge">
              {{ isSigning ? 'Signing…' : 'Sign challenge' }}
            </button>
          </div>
          <p v-if="errorMessage" class="notice notice--error">{{ errorMessage }}</p>
          <p v-if="successMessage" class="notice notice--success">{{ successMessage }}</p>
        </section>

        <section class="panel panel--result">
          <div class="panel__header">
            <h2>Signed proof bundle</h2>
            <span class="panel__hint">Paste back into Nomen</span>
          </div>
          <pre class="result">{{ proofJson || 'No signed proof yet.' }}</pre>
          <div class="actions">
            <button class="btn" :disabled="!proofJson || isCopying" type="button" @click="copyProof">
              {{ isCopying ? 'Copying…' : 'Copy JSON' }}
            </button>
          </div>
        </section>
      </section>
    </main>
  </div>
</template>
